[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino
upload_port = /dev/serial/by-path/platform-xhci-hcd.1-usb-0:1:1.0-port0
monitor_port = /dev/serial/by-path/platform-xhci-hcd.1-usb-0:1:1.0-port0

lib_deps =
    madhephaestus/ESP32Servo@^3.0.6

build_flags =
    -DDISABLE_ALL_LIBRARY_WARNINGS

monitor_speed = 115200
upload_speed  = 115200

