[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino
upload_port = /dev/serial/by-path/platform-xhci-hcd.0-usb-0:1:1.0-port0
monitor_port = /dev/serial/by-path/platform-xhci-hcd.0-usb-0:1:1.0-port0


lib_deps =
    bodmer/TFT_eSPI@^2.5.43

; TFT_eSPI pin config — ST7735 160×128  MOSI=23  SCLK=18  CS=5  DC=2  RST=4
build_flags =
    -DUSER_SETUP_LOADED=1
    -DST7735_DRIVER=1
    -DST7735_BLACKTAB=1
    -DTFT_WIDTH=128
    -DTFT_HEIGHT=160
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=5
    -DTFT_DC=2
    -DTFT_RST=4
    -DSPI_FREQUENCY=27000000
    -DSPI_READ_FREQUENCY=20000000
    -DDISABLE_ALL_LIBRARY_WARNINGS

monitor_speed = 115200
upload_speed  = 115200
